SRC_CPP := color.o distransform.o pyramids.o smooth.o sumpixels.o undistort.o demosaicing.o filter.o imgwarp.o \
thresh.o templmatch.o connectedcomponents.o improc_tables.o
PREFIX :=

include ../../Makefile.inc

