SRC_CPP := alloc.o arithm.o copy.o lapack.o matmul.o matop.o matrix.o umatrix.o stl.o mathfuncs.o dxt.o \
datastructs.o convert.o array.o stat.o tables.o algorithm.o rand.o kmeans.o parallel.o system.o
PREFIX :=

include ../../Makefile.inc

