C_OBJS=conn_mgr.o
ASM_OBJS=
COMPONENT=udp_conn.o
INTERFACES=
DEPENDENCIES=torrent printc mem_mgr_large sched valloc cbuf_mgr evt net_transport lock
IF_LIB=
OBJLIBS += $(POSIX_LIB)

include ../../Makefile.subsubdir

