C_OBJS=conn_mgr.o
ASM_OBJS=
COMPONENT=tcp_conn.o
INTERFACES=
DEPENDENCIES=torrent periodic_wake printc mem_mgr_large sched valloc timed_blk cbuf_mgr evt net_transport lock
IF_LIB=
OBJLIBS += $(POSIX_LIB)

include ../../Makefile.subsubdir

